networks:
  elk:
    driver: bridge

services:
  database:
    container_name: nsbp-database
    image: mysql:8.0.26
    ports:
      - 55555:3306
    volumes:
      - ./mysql:/var/lib/mysql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--skip-character-set-client-handshake'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: nsbp
      TZ: Asia/Seoul
    networks:
      - elk
    restart: unless-stopped

  redis:
    image: redis:7.2.4
    container_name: nsbp-redis
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}