spring:
  application:
    name: not-simple-board-project
  profiles:
    active: key

  jpa:
    properties:
      hibernate:
#        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: validate

  data:
    elasticsearch:
      repositories:
        enabled: false

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        SQL: debug
