### 댓글 등록
POST http://localhost:8080/v1/board/reply
Content-Type: application/json

{
  "post_id": 10,
  "content": "댓글 내용2"
}

### 댓글 수정
PATCH http://localhost:8080/v1/board/reply
Content-Type: application/json

{
  "id": 1,
  "content": "댓글 내용 수정"
}

### 댓글 삭제
DELETE http://localhost:8080/v1/board/reply
Content-Type: application/json

{
  "id": 2
}
